### PR TITLE
Move nebula-clients/node to the repo

### PR DESCRIPTION
**Pull request by laura-ding**

### CODE REVIEW

**Comment by avently** [comment]
Hello. Any news about merging this?

**Comment by avently** [comment]
@nianiaJR @laura-ding @dutor

**Comment by laura-ding** [comment]
> @nianiaJR @laura-ding @dutor

I will update the thrift file today. then it can merge.

**Review by jerryliang64 — APPROVED** [review]
LGTM

**Comment by avently** [comment]
Thank you, guys!

**Pull request merged**
