### PR TITLE
add GitHub workflow for unit testing and npm publish

### PR DESCRIPTION
**Pull request by wujjpp**
1. add auto unit tesing for pushing
2. add npm-publish workflow

### CODE REVIEW

**Comment by wujjpp** [comment]
@wey-gu 
1. auto unit tesing, https://github.com/wujjpp/nebula-node/runs/6814883959?check_suite_focus=true
2. for #9 , please setup `secrets.npm_token` for this project

https://github.com/wujjpp/nebula-node/blob/enhance-ci/.github/workflows/npm-publish.yml#L59

**Comment by wey-gu** [comment]
> @wey-gu
> 
> 1. auto unit tesing, https://github.com/wujjpp/nebula-node/runs/6814883959?check_suite_focus=true
> 2. for [publish to package repo #9](https://github.com/nebula-contrib/nebula-node/issues/9) , please setup `secrets.npm_token` for this project
> 
> https://github.com/wujjpp/nebula-node/blob/enhance-ci/.github/workflows/npm-publish.yml#L59

You are amazing @wujjpp 
I will request the org admin to do it tomorrow.

**Comment by wey-gu** [comment]
I guess you meant gh actions rather than gitlab 🙃

**Comment by wujjpp** [comment]
> I guess you meant gh actions rather than gitlab 🙃

@wey-gu GitHub

**Comment by wey-gu** [comment]
@wujjpp a token should be set to `npm_token` already, I will merge the PR to see if it's properly set.

**Review by wey-gu — APPROVED** [review]
Great Job, thanks!!!

**Pull request merged**
